// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1o8ZZWVEfSwyB0LBTsHzCNZcjWj7cKFI',
    appId: '1:691055716364:web:dd24a3090717044f592629',
    messagingSenderId: '691055716364',
    projectId: 'fuelwise-e9d64',
    authDomain: 'fuelwise-e9d64.firebaseapp.com',
    storageBucket: 'fuelwise-e9d64.firebasestorage.app',
    measurementId: 'G-NLCDCV1GEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMl3rWhR7oof0L-TtqhGDwn42kxq1zC8',
    appId: '1:691055716364:android:f236cf18a75b2411592629',
    messagingSenderId: '691055716364',
    projectId: 'fuelwise-e9d64',
    storageBucket: 'fuelwise-e9d64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzVhZgz1JrlpnSChzi2YKr0NMWLEK6ZjA',
    appId: '1:691055716364:ios:24eef23b7cc39833592629',
    messagingSenderId: '691055716364',
    projectId: 'fuelwise-e9d64',
    storageBucket: 'fuelwise-e9d64.firebasestorage.app',
    iosBundleId: 'br.unigra.fuelwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzVhZgz1JrlpnSChzi2YKr0NMWLEK6ZjA',
    appId: '1:691055716364:ios:24eef23b7cc39833592629',
    messagingSenderId: '691055716364',
    projectId: 'fuelwise-e9d64',
    storageBucket: 'fuelwise-e9d64.firebasestorage.app',
    iosBundleId: 'br.unigra.fuelwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1o8ZZWVEfSwyB0LBTsHzCNZcjWj7cKFI',
    appId: '1:691055716364:web:85d505b2bb011199592629',
    messagingSenderId: '691055716364',
    projectId: 'fuelwise-e9d64',
    authDomain: 'fuelwise-e9d64.firebaseapp.com',
    storageBucket: 'fuelwise-e9d64.firebasestorage.app',
    measurementId: 'G-9JTK1RLEN5',
  );
}
